wandb_version: 1

data:
  desc: null
  value:
    batch_size: 128
    color_jitter_strength: 0.0
    crop_scale:
    - 0.3
    - 1.0
    crop_size: 224
    image_folder: imagenet_full_size/061417/
    num_workers: 10
    pin_mem: true
    root_path: $replace_this_with_absolute_path_to_your_datasets_directory
    use_color_distortion: false
    use_gaussian_blur: false
    use_horizontal_flip: false
logging:
  desc: null
  value:
    folder: /home/brett/Desktop/tutorials/ijepa/ijepa/logs/tiny_vit
    write_tag: jepa
mask:
  desc: null
  value:
    allow_overlap: false
    aspect_ratio:
    - 0.75
    - 1.5
    enc_mask_scale:
    - 0.85
    - 1.0
    min_keep: 10
    num_enc_masks: 1
    num_pred_masks: 4
    patch_size: 14
    pred_mask_scale:
    - 0.15
    - 0.2
meta:
  desc: null
  value:
    copy_data: false
    load_checkpoint: false
    model_name: vit_tiny
    pred_depth: 12
    pred_emb_dim: 384
    read_checkpoint: null
    use_bfloat16: false
optimization:
  desc: null
  value:
    ema:
    - 0.996
    - 1.0
    epochs: 300
    final_lr: 1.0e-06
    final_weight_decay: 0.4
    ipe_scale: 1.0
    lr: 0.001
    start_lr: 0.0002
    warmup: 40
    weight_decay: 0.04
_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.15.11
    framework: huggingface
    huggingface_version: 4.33.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1719599415.854456
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.8.5
      5: 0.15.11
      6: 4.33.2
      8:
      - 2
      - 5
      - 9
      13: linux-x86_64
