_wandb:
    value:
        cli_version: 0.17.3
        python_version: 3.8.5
        t:
            1:
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            2:
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            3:
                - 23
                - 55
            4: 3.8.5
            5: 0.17.3
            6: 4.33.2
            8:
                - 2
                - 5
            12: 0.17.3
            13: linux-x86_64
