wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.17.2
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1719601819
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      3:
      - 23
      4: 3.8.5
      5: 0.17.2
      8:
      - 2
      - 5
      13: linux-x86_64
