wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.17.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1719601049
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 23
      4: 3.8.5
      5: 0.17.3
      8:
      - 2
      - 5
      13: linux-x86_64
